---
title: "Species' predicted length frequency distributions"
output: 
  pdf_document:
    fig_caption: false
geometry: margin=1in
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8,
  fig.height = 8, out.width = "100%")
```

```{r libraries, include=FALSE}
#install_cmdstan() 
library(MASS)
library(tidyverse)
library(here)
library(patchwork)
library(tidylog)
library(paletteer)
library(ggtext)
library(gtools)
library(cmdstanr)
library(posterior)
library(cowplot)
library(bayesplot)
library(ggrepel)
library(scales)
```


```{r set project directory path, include=FALSE}
tt_bin <- "C:/Users/sarahw69/AppData/Roaming/TinyTeX/bin/windows"

Sys.setenv(
  PATH = paste(
    tt_bin,
    Sys.getenv("PATH"),
    sep = .Platform$path.sep))

rm(list = ls())
project_dir <- here::here()

input_dir <- file.path(project_dir, "02_pipeline", "06_nectar", "stan_fits2")
output_dir <- file.path(project_dir, "03_graphics")
stan_file <- "01_code/fish_length_NegBinomial_parallelised_MPA.stan"
```


```{r import fits, include=FALSE}
fit_files <- list.files(
  input_dir,
  pattern = "^fit_.*\\.rds$",
  recursive = TRUE,
  full.names = TRUE
)

fits <- lapply(fit_files, readRDS)

names(fits) <- basename(fit_files) |>
  sub("^fit_", "", x = _) |>
  sub("\\.rds$", "", x = _)


names(fits)

input_files <- list.files(
  input_dir,
  pattern = "^model_inputs_.*\\.rds$",
  recursive = TRUE,
  full.names = TRUE
)

model_inputs <- lapply(input_files, readRDS)

names(model_inputs) <- basename(input_files) |>
  sub("^model_inputs_", "", x = _) |>
  sub("\\.rds$", "", x = _)

max_length <- read_csv(file.path(project_dir, "0_data", "02_data_clean", "species_list.csv")) |> 
  mutate(max_length = pmax(max_length_fb, max_length_foa, na.rm = TRUE), 
         fished = case_when(fished_rec == "y" ~ "Yes",
                            fished_rec == "n" ~ "No"),
         length_cat = case_when(
      max_length >= 75 ~ "75+",
      max_length >= 50 ~ "50-74",
      max_length >= 40 ~ "40-49",
      max_length >= 30 ~ "30-39",
      max_length >= 25 ~ "25-29",
      max_length >= 20 ~ "20-24",
      max_length >= 15 ~ "15-19",
      max_length >= 10 ~ "10-14",
      TRUE ~ NA_character_)) |> 
  select(-c(max_length_fb, max_length_foa))

```


```{r custom load functions, include=FALSE}

purrr::walk(
  list.files("01_code/functions", pattern = "\\.R$", full.names = TRUE),
  source)

```


```{r size dist plots}
species_list <- names(fits)

for (species_a in species_list){
  pred_curves <- PredictSpeciesCurves(
  species = species_a,
  fit_files = fit_files,
  model_inputs = model_inputs,
  master_bins = master_bins,
  time_years = c(1990, 2000, 2010, 2020),
  temp_change = c(0, 1, 5, 10),
  n_draws = 1000,
  ci_width = 0.80)
  
  p_two_panel <- PlotSpeciesDistribution(
  pred_curves,
  show_uncertainty = TRUE)
  
   print(p_two_panel)
}

```
