---
title: "Data cleaning"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r include=FALSE}

library(tidyverse)

#import data
rls <- read_csv('../Data/rls_m1_tasmania.csv')


```


```{r}

# create summary to see what to filter on 

rls_summary <- rls %>%  
  separate(survey_date, c('year', 'month', 'day'), sep='-', remove=FALSE) %>% #create a year column
  group_by(species_name) %>% 
  mutate(n_obs = sum(total), year_min = min(year), year_max = max(year), n_year = n_distinct(year), n_survey = n_distinct(survey_id), n_size_class = n_distinct(size_class)) %>% 
  ungroup() %>% 
  unite(year_span, year_min, year_max, sep = "-", remove = TRUE) %>% 
  distinct(species_name, .keep_all = TRUE) %>% 
  select(species_name, n_obs, year_span, n_year, n_survey, n_size_class)



```
What filtering requirements to use? I want to look at change over time, so 


```{r}
# filter 
rls2 <- rls %>%  
  separate(survey_date, c('year', 'month', 'day'), sep='-', remove=FALSE) %>% #create a year column
  group_by(species_name) %>% 
  mutate(n_obs = sum(total), year_min = min(year), year_max = max(year), n_year = n_distinct(year), n_survey = n_distinct(survey_id), n_size_class = n_distinct(size_class)) %>% 
  filter(n_obs >= 200) %>% 
  filter(n_year >=10) %>% 
  filter(n_size_class>= 3) %>% 
  ungroup() %>% 
  filter(species_name!='Unidentified fish (baitfish)') %>% 
   filter(species_name!='Arripis spp.') %>% 
   filter(species_name!='Arripis trutta') %>% 
   filter(species_name!='Cephaloscyllium laticeps') %>% 
   filter(species_name!='Pseudocaranx georgianus') %>% 
   filter(species_name!='Trachurus declivis') %>% 
  filter(species_name!='Urolophus cruciatus')

d <- d |> 
  filter(species!="Trachurus novaezelandiae"& # pelagic. yellowtail scad
           species!="Trachinops taeniatus"& # eastern hulafish
           species!="Trachinops caudimaculatus"& # southern hulafish
           #species!="Atypichthys strigatus"&
           #species!="Chromis hypsilepis"&
           species!="Pempheris multiradiata"&
           species!="Pempheris affinis"&
           #species!="Parma microlepis"&
           species!="Pseudolabrus luculentus"&
           species!="Parma unifasciata"&
           species!="Neoodax balteatus"&
           species!="Thalassoma lunare"&
           species!="Ostorhinchus limenus"&
           species!="Thalassoma lutescens"&
           species!="Hypoplectrodes maccullochi"&
           species!="Thalassoma amblycephalum"&
           species!="Upeneichthys lineatus"&
           species!="Pagrus auratus"&
           species!="Microcanthus joyceae"&
           species!="Pseudolabrus guentheri"&
           species!="Halichoeres nebulosus"&
           species!="Gerres subfasciatus"&
           species!="Mecaenichthys immaculatus"&
           species!="Scomber australasicus"&
           species!="Siphonognathus beddomei"&
           species!="Plagiotremus tapeinosoma"&
           species!="Eupetrichthys angustipes"&
           species!="Stethojulis interrupta"&
           species!="Pseudanthias squamipinnis"&
           species!="Austrolabrus maculatus"&
           species!="Dotalabrus aurantiacus"&
           species!="Scarus ghobban"&
           species!="Nemadactylus douglasii"&
           species!="Brachaluteres jacksonianus"&
           species!="Chelmonops truncatus"&
           species!="Acanthaluteres spilomelanurus"&
           species!="Nelusetta ayraud"&
           species!="Stethojulis bandanensis"&
           species!="Acanthurus nigrofuscus"&
           species!="Chaetodon flavirostris"&
           species!="Aracana aurita"&
           species!="Acanthopagrus australis"&
           species!="Trachurus declivis"&
           species!="Pseudocaranx dentex")

```

```{r}
table(rls2$species_name)
```

```{r}
## random code
uncount(total, .remove = FALSE) 
```

```{r}
ggplot(rls2, aes(size_class ))+geom_histogram()+facet_wrap(.~species_name, scales = 'free')
  
```

```{r}
rls2 <- rls2 %>% group_by(species_name, size_class) %>% 
  mutate(n_per_size_class=n()) %>% 
  ungroup()
```
```{r}
ggplot(rls2, aes(size_class, n_per_size_class))+
  geom_point()+
  facet_wrap(.~species_name, scales = 'free')
```

