
# === Prepare data for Stan fitting ============================================
# inputs: stan_data  = stan_data list generated by make_stan_data
#         init_fun   = init_fun function returned by make_stan_data
#         model_file = stan file ("fish_length_NegBinomial.stan")
# outputs: sample object
fit_model <- function(stan_data, init_fun, model_file) {
  mod <- cmdstan_model(model_file, 
                       cpp_options = list(stan_threads = TRUE), 
                       force_recompile = FALSE) # compile model
  
  fit <- mod$sample(
    data            = stan_data,  # === *** change for needs ===
    chains          = 3,          # *** 
    parallel_chains = 3,
    threads_per_chain = 2,
    iter_warmup     = 1000,        # ***
    iter_sampling   = 2000,        # ***
    init            = init_fun,
    adapt_delta     = 0.98,
    max_treedepth   = NULL
  )
  
  fit 
}